# Generated by Django 5.2.6 on 2025-09-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
